# Generated by Django 4.2.4 on 2023-08-08 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(auto_now_add=True, verbose_name='Отправка')),
                ('status', models.CharField(choices=[('success', 'success'), ('failure', 'failure')], default='success', max_length=10, verbose_name='Статус')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.distribution')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
