# Generated by Django 4.2.4 on 2023-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='time',
        ),
        migrations.RemoveField(
            model_name='distributionclient',
            name='distribution_settings',
        ),
        migrations.RemoveField(
            model_name='distributionclient',
            name='user',
        ),
        migrations.AddField(
            model_name='distribution',
            name='attempt',
            field=models.BooleanField(default=False, verbose_name='статус попытки'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='datetime',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата и время попытки'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='distribution_client',
            field=models.ManyToManyField(to='distribution.distributionclient', verbose_name='Клиент рассылки'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='Время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='ответ сервера'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='Время начала рассылки'),
        ),
        migrations.AddField(
            model_name='distributionclient',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='distributionclient',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='distributionclient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='distributionclient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема сообщения'),
        ),
    ]
