# Generated by Django 4.2.4 on 2023-08-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0003_distribution_user_delete_distributionclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='user',
        ),
        migrations.CreateModel(
            name='DistributionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.distribution', verbose_name='Настройки рассылки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Клиент рассылки',
                'verbose_name_plural': 'Клиенты рассылки',
            },
        ),
    ]
