# Generated by Django 4.2.4 on 2023-08-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_remove_distribution_user_distributionclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='time',
            field=models.TimeField(verbose_name='Отправка'),
        ),
    ]
