# Generated by Django 4.2.4 on 2023-08-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_remove_distributionclient_distribution_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='time',
        ),
        migrations.AddField(
            model_name='distribution',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала рассылки'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала рассылки'),
        ),
    ]
